@startuml ActivityDiagramVideo

partition "Diagrama de Vídeo" {
    partition "Modificar Vídeo" {
        (A)
        :Pesquisar vídeo;
        :Localizar vídeo;
        fork
        :Receber URL;
        fork again
        :Receber título;
        fork again
        :Receber descrição;
        fork again
        :Receber categoria;
        end fork
        stop
    }
    partition "Apagar Vídeo" {
        (B)
        :Pesquisar vídeo;
        :Localizar vídeo;
        :Confirmar exclusão;
        stop
    }  

    partition "Cadastrar Vídeo" {
        (C)
        :Receber URL;
        :Receber título;
        :Receber descrição;
        :Receber categoria;
        :Confirmar cadastro;
        stop
    }
}
@enduml