@startuml ClassDiagram

left to right direction

class User {
    -m_UserId : int
    -m_UserName : string
    -m_UserEmail : string
    -m_UserType : UserType
    +registerUser() : void
    +createToken() : void
    +deleteToken() : void
    +getUserId() : void
    +createCommentary(commentaryText: string) : Commentary
}

class Admin {
    +modifyCategory() : void
    +deleteVideo() : void
    +modifyMetaData() : void
    +modifyVideoUrl() : void
}

class Category {
    -m_CategoryId : int
    -m_CategoryTitle : string
    -m_CategoryUrl : string
    -m_CategorySubtitle : string
    -m_CategoryColor : byte[3]
    +m_CategoryComments : CategoryCommentary[]
    +m_CategoryExtraInfos : CategoryExtraInfos[]
    +m_CategoryAlterationsHistory : AlterationHistory[]
    +setCategoryTitle() : void
    +getCategoryTitle() : string
    +setCategoryUrl() : void
    +getCategoryUrl() : string
    +setCategorySubtitle() : void
    +getCategorySubtitle() : string
    +setCategoryColor() : void
    +getCategoryColor() : byte[3]
    +searchCategory() : Category[]
    +deleteCategory() : void
    +createCategory() : void
    +shareCategory() : string
    +filterCategory(): Category[]
}

class Commentary {
    -m_CommentaryId : int
    +m_AuthorName : string
    +m_CommentaryText : string
    +getCommentaryId() : void
}

class VideoCommentary {
   +m_VideoId : int
}

class CategoryCommentary {
    +m_CategoryId : int
}

class ExtraInfos {
    -m_ExtraInfosId : int
    +m_CreatorName : string
    +m_ExtraInfoCreatedAt : DateTime
    +m_ExtraInfoEditedAt : DateTime
    +m_ExtraInfoTitle: string;
    +m_ExtraInfoBody: string;
    +getExtraInfosId() : int
}

class VideoExtraInfos {
   +m_VideoId : int
}

class CategoryExtraInfos {
    +m_CategoryId : int
}

class Video {
    -m_VideoId : int
    -m_VideoCategory : Category
    -m_VideoMetadata : Metadata
    +m_VideoComments : VideoCommentary[]
    +m_VideoExtraInfos : VideoExtraInfos[]
    +m_VideoAlterationsHistory : VideoAlterationHistory[]
    +deleteVideoFromCategory() : void
    +searchVideo() : Video[]
    +searchVideoOnCategory() : Video[]
    +addVideoInCategory() : void
    +getMetadata() : Metadata
    +shareVideo() : string
    +filterVideos() : Video[]
}

class Metadata{
    -m_MetadataID : int
    -m_MetadataVideoLink : string
    -m_MetadataTitle : string
    -m_MetadataDescription : string
    -m_MetadataVideoYoutubeChannel : string
    +getMetadataId(): int
    +setMetadataTitle(): void
    +getMetadataTitle(): string
    +setMetadataDescription(): void
    +getMetadataDescription(): string
}

class AlterationHistory {
    -m_AlterationId : int
    +m_AlteratorName: string
    +m_LastAlteration: DateTime
    +m_Alteration: string
    +getAlterationId() : int
}

class VideoAlterationHistory {
    +m_VideoId : int
}

class CategoryAlterationHistory {
    +m_CategoryId : int
}

class Channel {
    -m_ChannelId : int
    +m_Creator : User
    -m_Private: bool
    -m_Participants: User[]
    +m_Contents: string[]
    +getChannelId() : int
    +setPrivacity() : void
    +getPrivacity() : bool
    +getParticipants() : User[]
    +searchChannel() : Channel[]
    +enterInAChannel() : void 
    +inviteLink() : string
    +createAContent() : string
}

enum UserType {
    NORMAL_USER = 1
    ADMIN_USER = 2
}

User <|-- Admin

VideoAlterationHistory --|> AlterationHistory
CategoryAlterationHistory --|> AlterationHistory

VideoCommentary --|> Commentary
CategoryCommentary --|> Commentary

VideoExtraInfos --|> ExtraInfos
CategoryExtraInfos --|> ExtraInfos

User "1"-up-"1" UserType

Video "1"*-down-"1" Metadata : Possui
Video "0..*" o-- "1" Category : Associa
Video "0..*"*--"1" User : Adiciona 

Channel "0..*"*--"1" User : Possui/Participa

Category "0..*"*--"1" User : Cria

VideoCommentary "0..*"*--"1" User : Cria
VideoCommentary "0..*"*-up-"1" Video : Possui

VideoExtraInfos "0..*"*--"1" User : Cria
VideoExtraInfos "0..*"*-up-"1" Video : Possui

VideoAlterationHistory "0..*"*--"1" User : Cria
VideoAlterationHistory "0..*"*-up-"1" Video : Possui

CategoryCommentary "0..*"*--"1" User : Cria
CategoryCommentary "0..*"*--"1" Category : Possui

CategoryExtraInfos "0..*"*--"1" User : Cria
CategoryExtraInfos "0..*"*--"1" Category : Possui

CategoryAlterationHistory "0..*"*--"1" User : Cria
CategoryAlterationHistory "0..*"*--"1" Category : Possui

note bottom of User : {createToken()} Cria um token de acesso, equivalente a fazer login.
note bottom of User : {deleteToken()} Equivalente a fazer logout. Responsável por expirar o token.
note left of Channel : {searchChannel() : Channel[]} e {enterInAChannel() : void} Somente estaráo disponíveis se o Channel não for privado ({getPrivacity() : bool} retornar false).
note bottom of Metadata : São informações vindas diretamente do Youtube.

@endtuml
