@startuml PackageDiagram

left to right direction

package "Camada de Aplicação" as CamadaDeApresentação {
    package Views
    package React
}

package "Lógica de Aplicação" as LógicaDaAplicação {
    package Objetos_de_controle
    package "Lógica de Negócio" as LógicaDeNegócio {
        package "Vídeo e categoria de vídeos"
        package Autenticação
        package Administração
    }
}

package Dados {
    package SGBD
    package Motor_de_pesquisa 
    package Sistema_de_arquivos
}

Views <.. React
Views .down.> Objetos_de_controle
SGBD <.. Motor_de_pesquisa
Motor_de_pesquisa ..> Sistema_de_arquivos
Objetos_de_controle <..> LógicaDeNegócio
LógicaDeNegócio .up.> Motor_de_pesquisa
@enduml
